print('\033[1m{:^40}\033[m'.format('>>> FOLHA DE PAGAMENTO <<<'))
valor_hora = float(input('VALOR HORA: R$ '))
hora = int(input('HORAS TRABALHADAS: '))
print('-'*40)
salario = valor_hora*hora
ir = ((salario*11)/100)
inss = ((salario*8)/100)
sindicato = ((salario*5)/100)
liquido = salario-(ir+inss+sindicato)
print(f'> SALÁRIO BRUTO: R$ {salario:.2f}')
print(f'> DESCONTO IR (11%): R$ {ir:.2f}')
print(f'> DESCONTO INSS (8%): R$ {inss:.2f}')
print(f'> DESCONTO SINDICATO (5%): R$ {sindicato:.2f}')
print(f'> SALÁRIO LÍQUIDO: R$ {liquido:.2f}')
